

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace tutorial
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class NorthwindEntities : DbContext
{
    private bool _isInitialized = false;

    public NorthwindEntities()
        : base("name=NorthwindEntities")
    {
        Initialize();
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }

    protected internal void Initialize()
    {
        if (!_isInitialized)
        {
            _isInitialized = true;

            // EF 6.0.1 throws an exception, unless we first probe the provider types.
            var type1 = typeof(System.Data.Entity.SqlServer.SqlProviderServices);
        }
    }

    public virtual DbSet<Product> Products { get; set; }

}

}

